### PR TITLE
Bump to latest version (7.0.5-10)

### PR DESCRIPTION
**Pull request by dreamsInDigital**
Bumps to current imagemagick version 7.0.5-9. Will need to 🎩  and make sure there are no breaking changes, since its a version 6->7 bump.

@haani 
@nickhoffman

### CODE REVIEW

**Comment by nickhoffman** [comment]
Thanks for doing this, @dreamsInDigital. Much appreciated. How urgently does this PR need to be shipped?

**Comment by nickhoffman** [comment]
BTW, after this has been merged, a new deploy will need to be made for Growth Tools. In the past, I've done that with [an empty commit](https://github.com/Shopify/growth_tools/commit/f5482e).

**Comment by dreamsInDigital** [comment]
@nickhoffman we should get it in within the next few days if we can

**Comment by nickhoffman** [comment]
Bumped to ImageMagick v7.0.5-10 because -9 has been removed.

**Comment by nickhoffman** [comment]
Growth Tools' [staging site](https://growth-tools-staging.herokuapp.com/tools) is using ImageMagick v7.0.5-10 now:

```bash
$ heroku run rails console --app growth-tools-staging -s standard-1x

irb> `identify --version`
=> "Version: ImageMagick 7.0.5-10 Q16 x86_64 2017-06-05 http://www.imagemagick.org\nCopyright: © 1999-2017 ImageMagick Studio LLC\nLicense: http://www.imagemagick.org/script/license.php\nFeatures: Cipher DPC HDRI OpenMP \nDelegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jpeg lcms lqr lzma openexr png tiff wmf x xml zlib\n"
```

Next step is to 🎩 on the staging site.

**Comment by nickhoffman** [comment]
Staging's being used for something else at the moment, so I'll need to update it again before the 🎩

**Comment by dreamsInDigital** [comment]
@nickhoffman Staging free today for 🎩 ? Would be good to get this bumped today if we can

**Comment by nickhoffman** [comment]
@dreamsInDigital, yeah, I'm going to today.

**Comment by nickhoffman** [comment]
Everything looks good on staging. @dreamsInDigital, :shipit:, then trigger a deploy in Growth Tools production to get the production app to use the new version of ImageMagick.

#### Logo Maker Comparisons

1. [staging](https://growth-tools-staging.herokuapp.com/tools/logo-maker/show/TVRYQ0s5NlptSDlUNW9PRlg2cjcvZz09LS1xTUN2akh5M3c5dXhFb0JTSmtrcC93PT0=--a274b57412c3ffd96f864235114d584b67e898a0) vs [production](https://www.shopify.com/tools/logo-maker/show/Y2tWVzZnZHhoci9YRytDSXlKWFNRUT09LS0yRklxS0Y0bGdwZzJ2eEpqK05DdnVRPT0=--dd61f0eca32a5622f11a8e83df92129e37a9c844)

2. [staging](https://growth-tools-staging.herokuapp.com/tools/logo-maker/show/RENnVGxqVjVwK0NpdkdOUG1zdzI3QT09LS1manNzUXppVVF2Q1c1Sk9WL3Z5Zlh3PT0=--30109fb04c3cf8224a9145fa9a43ba73e76466c3) vs [production](https://www.shopify.com/tools/logo-maker/show/b3NNMDBqNWwwZlVqRDV4KzE0eFJ1Zz09LS13SkxMQ2REeVhNRzZOaWJ0VXdjL1p3PT0=--f1fbd576b376f1dea4f72135d9074d466b04d7cd)

3. [staging](https://growth-tools-staging.herokuapp.com/tools/logo-maker/show/S1RaZlpLSjM2NytLR1QzQXpSZVZoQT09LS1ja1o4ZkJpVjdXbFZ0dmRmWENtejhBPT0=--a780e667629b27a098de442ced7baba53b57c162) vs [production](https://www.shopify.com/tools/logo-maker/show/TXZBN3U1MngrTGFmNGJJM1NYemFNdz09LS1kL3RKZW9NUzRqYjBjajEvRUlaY3BnPT0=--d3e2a60f36c91f4b2d1c8fa8d079607655ef39aa)

#### Business Card Maker

1. [staging](https://growth-tools-staging.herokuapp.com/tools/business-card-maker/show/ZldieUZLM1R2TDlOQkwrN2RybTFWZz09LS1JT0kyRTVsOU5Cd3dFYXdBTk1GVEFRPT0=--ee234cb2e5b8fb08abb2191c25c8b165dc61a4ff) vs [production](https://www.shopify.com/tools/business-card-maker/show/TnVnSVhVaFNXbDkzUmlCYXlTbDRLUT09LS1EbWpkTUpiaVpheEhvRnNlR2xYcHhBPT0=--f16ce22c3706c27b3e20a088530e6b21be852641)

2. [staging](https://growth-tools-staging.herokuapp.com/tools/business-card-maker/show/c1NzcWxHOTU2TFhaWE5KbWNhN1NMdz09LS1ya0tnNlR6RnNvYnB3NHYrUVU5TTBRPT0=--be0e8eb3bc192668b08c53c92fe16bf66a5b35de) vs [production](https://www.shopify.com/tools/business-card-maker/show/UU5LU3NJK2lIdld1ZXN4MEliZHV0Zz09LS1sYlFHOGRhdWRKNkM0bFduekp2anNBPT0=--1b2fbc8cfedec9ddf5fea8340c3d51477406a482)

#### Invoice Generator

1. [staging](https://growth-tools-staging.herokuapp.com/pos/invoice-generator/show/bkdvMGh4amhLSUNZejNQK3gyRGN1UT09LS1LVU1Fb2FPdklVK0ZQTTZGbHhvN2tBPT0=--1fe6cab6e470a548350248dd21b050950e12add0) vs [production](https://www.shopify.com/pos/invoice-generator/show/a0JyeWRjODhmQnJ1RXRqclhKeWNEUT09LS1oSGNQZ01SN0RtY1V2QS9wOG1ham5nPT0=--7b6b8049044fd464af81e8c7cca68d56ce0009d3)

2. [staging](https://growth-tools-staging.herokuapp.com/pos/invoice-generator/show/ZzRPN1g4eG13aUpKR2VIRnZWUlpyZz09LS1tVXdNSUVvOFdNWExuUGNMc05VeXh3PT0=--80c4ccaea503c4bdd2a7319e3b6754a38cc629ba) vs [production](https://www.shopify.com/pos/invoice-generator/show/a3RoMlFGWkE0STVzNmdreHo2ZnR4Zz09LS00MHJJNWxIUDFnUkFZV2d6WngwMHlBPT0=--bb8481e5103665b822b8969d43ad93c880cb2cdf)

**Pull request merged**
